version: '1.0.{build}'

image: Visual Studio 2019

init:
  # - vcpkg install sdl2:x64-windows
  # - vcpkg integrate install

platform:
  - x64
 
configuration:
  - Debug

before_build:
  - cmake -G "Visual Studio 16 2019" -A x64 .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\01-basic-game-dev.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\01-1-hello-world\%CONFIGURATION%\01-1-hello-world.exe'

cache: c:\tools\vcpkg\installed\