version: '1.0.{build}'

image: Visual Studio 2019

init:

platform:
  - x64
 
configuration:
  - Release

before_build:
  - set path=c:\Program Files (x86)\WiX Toolset v3.11\bin;%path%
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_BUILD_TYPE=Release

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\WinMoBubbles.sln