image: leanid/fedora_latest
pipelines:
  default:
    - step:
        name: Build artifacts
        script:
          - git clean -df
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Release
          - cmake --build . -j6
          - cmake --build . -j6 --target installer-unix-ALL
    - step:
        name: Save new version
        script:
          - git add version.txt
          - git commit -m "[skip CI]"
    # - step:
    #     name: Deploy artifacts
    #     # trigger: manual  # Uncomment to make this a manual deployment.
    #     script:
    #       - pipe: atlassian/bitbucket-upload-file:0.3.2
    #         variables:
    #           BITBUCKET_USERNAME: $BITBUCKET_USERNAME
    #           BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
    #           FILENAME: '/opt/atlassian/pipelines/agent/build/build/installer_unix/output/WinMoBubbles.zip'