image: leanid/fedora_latest
pipelines:
  default:
    - step:
        script:
          - git clean -df
          - mkdir build
          - cd build
          - cmake ..
          #- cmake -configure .
          #- cmake -generate .
          - make -j6
